CREATE TABLE MAINTABLE (
   TABLE_NO   NUMBER      NOT NULL,
   TOTAL_PRICE   NUMBER      NULL
);



CREATE TABLE MENU (
   MENU   NVARCHAR2(20)      NOT NULL,
   RPICE   NUMBER      NOT NULL,
   MENU_YN   NVARCHAR2(10)      NULL
);

CREATE TABLE JUMUN (
   ORDER_NO   NUMBER      NOT NULL,
   ORDER_DATE   DATE      NULL,
   TABLE_NO   NUMBER      NOT NULL,
   MENU   NVARCHAR2(20)      NOT NULL,
   O_NUM   NUMBER      NULL 
);

CREATE TABLE PAYMENT (
   PAY_NO   NUMBER      NOT NULL,
   TABLE_NO   NUMBER      NOT NULL,
   ORDER_NO   NUMBER      NOT NULL,
   PAY_DATE   DATE      NULL,
   PAY_METHOD   NVARCHAR2(10)      NULL
);

CREATE TABLE RECEIPT (
   RE_NO   NUMBER      NOT NULL
);

ALTER TABLE MAINTABLE ADD CONSTRAINT PK_MAINTABLE PRIMARY KEY (
   TABLE_NO
);

ALTER TABLE ORDER ADD CONSTRAINT PK_ORDER PRIMARY KEY (
   ORDER_NO
);

ALTER TABLE MENU ADD CONSTRAINT PK_MENU PRIMARY KEY (
   MENU
);

ALTER TABLE PAYMENT ADD CONSTRAINT PK_PAYMENT PRIMARY KEY (
   PAY_NO
);

ALTER TABLE RECEIPT ADD CONSTRAINT PK_RECEIPT PRIMARY KEY (
   RE_NO
);


INSERT INTO MENU VALUES('가정식백반',6000 ,'Y');
INSERT INTO MENU VALUES('칼국수',7000 ,'Y');
INSERT INTO MENU VALUES('수제비',7000 ,'Y');
INSERT INTO MENU VALUES('장칼국수',7000 ,'Y');
INSERT INTO MENU VALUES('된장찌개',7000 ,'Y');
INSERT INTO MENU VALUES('김치찌개',7000 ,'Y');
INSERT INTO MENU VALUES('순두부찌개',7000 ,'Y');
INSERT INTO MENU VALUES('동태찌개',8000 ,'Y');
INSERT INTO MENU VALUES('청국장',7000 ,'Y');
INSERT INTO MENU VALUES('부대찌개',8000 ,'Y');
INSERT INTO MENU VALUES('김치볶음밥',7000 ,'Y');
INSERT INTO MENU VALUES('삼겹살',13000 ,'Y');
INSERT INTO MENU VALUES('닭볶음탕(중)',30000 ,'Y');
INSERT INTO MENU VALUES('닭볶음탕(대)',35000 ,'Y');
INSERT INTO MENU VALUES('제육볶음(중)',20000 ,'Y');
INSERT INTO MENU VALUES('제육볶음(대)',23000 ,'Y');
INSERT INTO MENU VALUES('오징어볶음(중)',20000 ,'Y');
INSERT INTO MENU VALUES('오징어볶음(대)',23000 ,'Y');
INSERT INTO MENU VALUES('옻오리',60000 ,'Y');
INSERT INTO MENU VALUES('옻닭',60000 ,'Y');
INSERT INTO MENU VALUES('닭백숙',60000 ,'Y');
INSERT INTO MENU VALUES('소주',4000 ,'Y');
INSERT INTO MENU VALUES('맥주',4000 ,'Y');
INSERT INTO MENU VALUES('막걸리',3000 ,'Y');
INSERT INTO MENU VALUES('음료수',2000 ,'Y');